# Jasypt Properties
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

# DB Configs
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campaign_master_db
    username: root
    password: ENC(KcoEjxZOPdgAdOMRcSkr3rA2Rs2e+rg/)
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configs
  jpa:
    hibernate:
      ddl-auto: update
    # properties.hibernate.format_sql: true
    # properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    # show-sql: true

# API Configs
server:
  servlet:
    context-path: /campaign-master/api/v1
    encoding:
      charset: UTF-8
      force-response: true

# Base URL
base:
  url: http://localhost:8080

# Logging
logging:
  file:
    parent: "./logs"
    name: "campaign-master"
  pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
